### ISSUE TITLE
spi_master_transfer implementation not following mbed HAL

### ISSUE THREAD

**Issue by marcuschangarm** [ARMmbed/mbed-hal-ksdk-mcu#42] opened 2015-10-20 12:07 UTC
The buffer length should be in number of word, not bytes.

https://github.com/ARMmbed/mbed-hal/blob/master/mbed-hal/spi_api.h#L141-L153

**Comment by marcuschangarm** [comment] 2015-10-20 12:08
@hugo regarding our earlier discussion.

**Comment by hugovincent** [comment] 2015-10-20 12:50
Thanks @marcuschangarm ... [OT] that API looks a little hard to use safely. For example are the `void *buf`s byte aligned, or machine-word aligned, or packed words?

**Comment by 0xc0170** [comment] 2015-10-20 12:51
Thanks for catching this, I am currently going through mbed-hal doxygen. This is an error in the docs, the size should be in bytes

**Comment by 0xc0170** [comment] 2015-10-20 12:56
Freescale KSDK targets and STM32F4 targets use bytes, therefore this was a typo.

**Comment by marcuschangarm** [comment] 2015-10-20 13:01
You really want to go there?

**Comment by hugovincent** [comment] 2015-10-20 13:02
@0xc0170 documenting that sizes are in bytes still doesn't answer the question above ("are the void *bufs byte aligned, or machine-word aligned, or packed bit_width-long words?") and is still unsafe ...

**Comment by hugovincent** [comment] 2015-10-20 13:07
(I just noticed you deprecated `bit_width`.... guess that means we only support 8-bit transfers for now?)

**Comment by 0xc0170** [comment] 2015-10-20 13:07
@marcuschangarm  I sent PR to fix the doc typo, provide a feedback there. We can either fix typo or fix the 2 implementations.

**Comment by 0xc0170** [comment] 2015-10-20 13:12
@hugovincent the buffers are accessed according to a protocol bit - https://github.com/ARMmbed/mbed-hal-ksdk-mcu/blob/master/source/spi_api.c#L235. 

```
transfer_format_bits(32bit);
transfer(buffer, sizeof(buffer));
```

**Comment by 0xc0170** [comment] 2015-10-21 08:33
@marcuschangarm I'll close this as it was resolved. Sorry for inconvenience. I can help to fix any issues caused by this

**Closed by 0xc0170** 2015-10-21 08:33 UTC
